name       : perl-http-negotiate
version    : 6.01
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/G/GA/GAAS/HTTP-Negotiate-6.01.tar.gz : 1c729c1ea63100e878405cda7d66f9adfd3ed4f1d6cacaca0ee9152df728e016
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : HTTP::Negotiate - choose a variant to serve
description: |
    This module provides a complete implementation of the HTTP content negotiation algorithm specified in draft-ietf-http-v11-spec-00.ps chapter 12. Content negotiation allows for the selection of a preferred content representation based upon attributes of the negotiable variants and the value of the various Accept* header fields in the request.
rundeps    :
    - perl-http-message
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
